// fetchProperties
export const FETCH_PROPERTIES_REQUESTS = 'FETCH_PROPERTIES_REQUESTS';
export const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS';
export const FETCH_PROPERTIES_ERROR = 'FETCH_PROPERTIES_ERROR';

// fetchPropertiesbyID
export const FETCH_PROPERTIES_BY_ID_REQUESTS = 'FETCH_PROPERTIES_BY_ID_REQUESTS';
export const FETCH_PROPERTIES_BY_ID_SUCCESS = 'FETCH_PROPERTIES_BY_ID_SUCCESS';
export const FETCH_PROPERTIES_BY_ID_ERROR = 'FETCH_PROPERTIES_BY_ID_ERROR';


//add properties

export const ADD_PROPERTY_POST = 'ADD_PROPERTY_POST';
export const ADD_PROPERTY_ERROR = 'ADD_PROPERTY_ERROR';


//delete property
// export const DELETE_PROPERTY = 'DELETE_PROPERTY';
// export const DELETE_PROPERTY_ERROR = 'DELETE_PROPERTY_ERROR';
// export const FETCH_DELETE_SUCCESS = 'FETCH_DELETE_SUCCESS';