// fetchProperties
export const FETCH_PROPERTIES_REQUESTS = 'FETCH_PROPERTIES_REQUESTS';
export const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS';
export const FETCH_PROPERTIES_ERROR = 'FETCH_PROPERTIES_ERROR';

// fetchPropertiesbyID
export const FETCH_PROPERTIES_BY_ID_REQUESTS = 'FETCH_PROPERTIES_BY_ID_REQUESTS';
export const FETCH_PROPERTIES_BY_ID_SUCCESS = 'FETCH_PROPERTIES_BY_ID_SUCCESS';
export const FETCH_PROPERTIES_BY_ID_ERROR = 'FETCH_PROPERTIES_BY_ID_ERROR';
